name: design_system
description: "A new Flutter package project."
version: 0.0.1
homepage:

resolution: workspace

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/background.png
    - assets/background.svg
    - assets/icon-white.svg
    - assets/icon.svg
    - assets/logo-horizontal-signature-white.svg
    - assets/logo-horizontal-signature.svg
    - assets/logo-vertical-signature-white.svg
    - assets/logo-vertical-signature.svg
    - assets/logo-white.svg
    - assets/logo.svg


